include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FactoryLayoutPrefs

FactoryLayoutPrefs_FILES = FLRootListController.m
FactoryLayoutPrefs_FRAMEWORKS = UIKit
FactoryLayoutPrefs_PRIVATE_FRAMEWORKS = Preferences
FactoryLayoutPrefs_INSTALL_PATH = /Library/PreferenceBundles
FactoryLayoutPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
